return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "vimdoc",
      "html",
      "javascript",
      "json",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "json5",
      "jsonc",
      "regex",
      "tsx",
      "ninja",
      "rst",
      "toml",
      "typescript",
      "vim",
      "yaml",
      "go",
      "ocaml",
      "astro",
      "clojure",
    },
  },
}
